.TH "MICAH" "1" "" "" "Micah Elliot Halter Manual"
.hy
.SH NAME
.PP
Micah Elliot Halter - a developer, researcher, and bartender
.SH SYNOPSIS
.PP
\f[B]micah\f[R] [\f[B]--student\f[R]] [\f[B]--employee\f[R]] [\f[B]--admin\f[R] \f[I]systems\f[R]| \f[I]databases\f[R]] [\f[B]--developer\f[R]] [\f[B]--researcher\f[R]]
.SH DESCRIPTION
.PP
I have been interested in computer science since I was six years old,
and have built up an unmatched passion for the field. I have extensive
experience in software development and research from internships,
projects, and competitions. I graduated from the Georgia Institute of
Technology with a Bachelor of Science in Computer Science with a focus
in system architecture and theory, and am working as a Researcher at the
Georgia Tech Research Institute.
.SH OPTIONS
.TP
.B \f[B]--student\f[R]
.RS
\f[I]Master of Science in Computer Science\f[R] - \f[B]Georgia Institute
of Technology\f[R] - \f[I]Dec\ 2021\f[R]
.IP
.nf
\f[C]
* Specialization in Machine Learning
\f[R]
.fi
.PP
\f[I]Bachelor of Science in Computer Science\f[R] - \f[B]Georgia
Institute of Technology\f[R] - \f[I]May\ 2019\f[R]
.IP
.nf
\f[C]
* Concentration in system architecture and theory

* Dean\[cq]s List Fall 2015, Spring 2016, Fall 2016, Fall 2018, Spring
2019
\f[R]
.fi
.PP
\f[I]Bachelor of Science in Computer Science\f[R] - \f[B]Hong Kong
University of Science and Technology\f[R] - \f[I]Dec\ 2017\f[R]
.IP
.nf
\f[C]
* Studied abroad
\f[R]
.fi
.RE
.TP
.B \f[B]--employee\f[R]
.RS
\f[I]Georgia Tech Research Institute\f[R] - \f[B]Research
Scientist\f[R] - \f[I]Jun\ 2019-Present\f[R]
.IP
.nf
\f[C]
* Lead contributor to research projects sponsored by large entities
DARPA, NIH, DOD, and ONR

* Wrote and published peer reviewed conference and journal papers to
communicate research findings to the greater research community

* Contributed and participated in white paper and proposal writing to
bring in more funding for new and on-going projects

* Delivered applied research projects to sponsors such as source code,
web applications, and technical reports

\f[R]
.fi
.PP
\f[I]Georgia Tech Research Institute\f[R] - \f[B]Undergraduate Research
Assistant\f[R] - \f[I]Jan\ 2016-May\ 2019\f[R]
.IP
.nf
\f[C]
* Lead contributor to research projects sponsored by large entities NIH
and ONR

* Wrote and published a peer reviewed journal paper to communicate
research findings to the greater research community

* Delivered applied research projects to sponsors such as source code,
web applications, and technical reports

* Predicting crimes in Portland, OR using temporal and geographic
features derived from crime statistics and GIS data

\f[R]
.fi
.PP
\f[I]The Boeing Company\f[R] - \f[B]Software Development
Intern\f[R] - \f[I]May\ 2016-Aug\ 2017\f[R]
.IP
.nf
\f[C]
* Developed a security auditing tool suite for Red Hat Enterprise Linux
7 to maintain hardened security on classified servers

* Developed a web application in C#, HTML, and JavaScript to view and
analyze network traffic

* Developed several system administration scripts as needed by team
members to complete tasks such as emailing system logs and automatic
server backups

* Organized and led a software development team to create a minimum
viable product of a Kanban board web application

* Pitched the Kanban board prototype to management to form a team to
continue development of the application after I left

* Documented and executed an upgrade plan for the company\[cq]s identity
management servers

* Developed an Outlook-integrated conference room mapping tool in C#

\f[R]
.fi
.RE
.TP
.B \f[B]--admin\f[R] \f[I]systems\f[R]
Through work opportunities and personal projects, I have had extensive
experience with the configuration, hardening, and maintenance of various
Linux distributions, including:
.RS
.IP
.nf
\f[C]
* Red Hat Enterprise Linux

* Debian, Ubuntu

* Arch Linux
\f[R]
.fi
.RE
.TP
.B \f[B]--admin\f[R] \f[I]databases\f[R]
Through my work experiences I have become skilled in many database
languages including MySQL, PostgreSQL, SQLite, and SQL Server. These
experiences range from designing a full database schema, administrating
and managing an existing database, and writing queries to parse through
the data.
.TP
.B \f[B]--developer\f[R]
I have worked on several development projects in both work environments
and personally using a plethora of different programming languages and
paradigms
.TP
.B \f[B]--researcher\f[R]
While working at the Georgia Tech Research Institute, I have found that
I love being involved with research projects. I enjoy taking charge of
open ended questions and exploring new methods and ways of tackling
tough problems.
.SH PROJECTS
.PP
\f[B]AlgebraicJulia\f[R] -
<https://github.com/AlgebraicJulia>
.IP
.nf
\f[C]
* A GitHub Organization for a collection of Julia packages for defining
modeling frameworks as generalized algebraic theories

* Includes Julia packages such as Catlab.jl and AlgebraicPetri.jl

* A category theory approach to defining metamodeling tasks for
representing, composing, selecting, and tuning scientific models

* Research funded by the Defense Advanced Research Projects Agency
(DARPA)
\f[R]
.fi
.PP
\f[B]Petri.jl\f[R] -
<https://github.com/mehalter/Petri.jl>
.IP
.nf
\f[C]
* A stochastic petri net modeling framework for the Julia programming
language

* Allow petri nets to be compiled to Gillespie and differential equation
based simulations
\f[R]
.fi
.PP
\f[B]VirtualEnv.jl\f[R] -
<https://github.com/mehalter/VirtualEnv.jl>
.IP
.nf
\f[C]
* Self-contained virtual environments for the Julia programming language

* A reimplementation of \f[C]venv\f[R] from Python in Julia
\f[R]
.fi
.PP
\f[B]Corsair Database\f[R]
.IP
.nf
\f[C]
* Research funded by the Office of Naval Research (ONR)

* Developed a web application for viewing and analyzing sonar SAS data
using Go, Python, and PostgresDB deployed with Docker and Drone.io

* Engineered a database for managing scientific experiments to utilize
the speed and efficiency of using a rigid relational database, while
being flexible enough to handle the changing data requirements of
scientific experimentation
\f[R]
.fi
.SH NOTES
.PP
Outside of the field of computer science I have many hobbies and
passions including Ultimate Frisbee, coffee, and music.
.PP
At Georgia Tech and the greater Atlanta area, I am a very active member
of the Ultimate Frisbee community. This includes playing on multiple
competitive teams throughout the years and competing in tournaments
nationally and globally.
.PP
I have been an avid coffee enthusiast for several years, frequenting
many coffee shops, getting to know local coffee roasters and baristas,
and hand brewing my own craft coffee.
.PP
Growing up I was very involved with band and played many instruments
including piano and flute. Nowadays I don\[cq]t play very often, but
love to attend concerts and live music events.
.SH SEE ALSO
.PP
Phone: +1 704 490 9840
.PP
Email: <micah\[at]mehalter.com>
.PP
GPG: BEB8 056E 542A 33EB 8A4B 081F 723F 998E 98D9
3D50 (http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0x723F998E98D93D50).PP
GPG: 4AC9 4692 18E3 1BCE 147F 1060 E51C 3EA3 BEB5
D4A9 (http://keys.gnupg.net/pks/lookup?op=vindex&fingerprint=on&search=0xE51C3EA3BEB5D4A9)
.PP
Website: <https://mehalter.com>
.PP
Git: <https://git.mehalter.com/mehalter>
.SH AUTHORS
Micah Elliot Halter.
