.TH "MICAH" "1" "" "" "Micah Elliot Halter Manual"
.hy
.SH NAME
.PP
Micah Elliot Halter - a developer, researcher, and bartender
.SH SYNOPSIS
.PP
\f[B]micah\f[R] [\f[B]--student\f[R]] [\f[B]--employee\f[R]] [\f[B]--admin\f[R] \f[I]systems\f[R]| \f[I]databases\f[R]] [\f[B]--developer\f[R]] [\f[B]--researcher\f[R]]
.SH DESCRIPTION
.PP
I have been interested in computer science since I was six years old,
and have built up an unmatched passion for the field. I have extensive
experience in software development and research from internships,
projects, and competitions. I graduated from the Georgia Institute of
Technology with a Bachelor of Science in Computer Science with a focus
in system architecture and theory, and am working as a Researcher at the
Georgia Tech Research Institute.
.SH OPTIONS
.TP
.B \f[B]--student\f[R]
.RS
\f[I]Bachelor of Science in Computer Science\f[R] - \f[B]Georgia Institute of Technology\f[R] - \f[I]May 2019\f[R]
.IP
.nf
\f[C]
* Concentration in system architecture and theory

* Dean\[cq]s List Fall 2015, Spring 2016, Fall 2016, Fall 2018, Spring
2019
\f[R]
.fi
.PP
\f[I]Bachelor of Science in Computer Science\f[R] - \f[B]Hong Kong University of Science and Technology\f[R] - \f[I]Dec 2017\f[R]
.IP
.nf
\f[C]
* Studied abroad
\f[R]
.fi
.RE
.TP
.B \f[B]--employee\f[R]
.RS
\f[I]Georgia Tech Research Institute\f[R] - \f[B]Researcher\f[R] - \f[I]May 2019-Present\f[R]
.IP
.nf
\f[C]
* Using NetFlow data and machine learning to detect possibly compromised
machines on a network

* Developing and implementing a new methodology to programmatically
represent and manipulate models at the semantic level

\f[R]
.fi
.PP
\f[I]Georgia Tech Research Institute\f[R] - \f[B]Student Researcher\f[R] - \f[I]Jan 2016-May 2019\f[R]
.IP
.nf
\f[C]
* Implementing a relational database schema to enhance sonar research

* Developed a machine learning based crime forecasting system using past
crime and geographical data

* Developed a wearable technology based 911 communication assistance tool

\f[R]
.fi
.PP
\f[I]Kindred Spirits Atlanta, LLC\f[R] - \f[B]Co-Owner and Bartender\f[R] - \f[I]Dec 2018-Present\f[R]
.IP
.nf
\f[C]
* Cater events with bartending and mixology services

* Create curated cocktail menus for events with innovative and complex
recipes to meet the needs of all event attendees

* Engage with curstomers and provide outstanding service to build customer
relations and increase company value

* Maintain and file all necessary legal documents to ensure legitimacy of
the business

\f[R]
.fi
.PP
\f[I]The Boeing Company\f[R] - \f[B]IT Intern\f[R] - \f[I]May 2017-Aug 2017\f[R]
.IP
.nf
\f[C]
* Developed a security auditing tool suite for Red Hat Enterprise Linux 7

* Developed a web-based data visualization tool

* Developed several system administration scripts as needed by team
members

\f[R]
.fi
.PP
\f[I]The Boeing Company\f[R] - \f[B]IT Intern\f[R] - \f[I]May 2016-Aug 2016\f[R]
.IP
.nf
\f[C]
* Documented and executed an upgrade plan for the company\[cq]s identity
management servers

* Developed an Outlook-integrated conference room mapping tool

* Designed and began development of a web-based Kanban board tool

\f[R]
.fi
.RE
.TP
.B \f[B]--admin\f[R] \f[I]systems\f[R]
Through work opportunities and personal projects, I have had extensive
experience with the configuration, hardening, and maintenance of various
Linux distributions, including:
.RS
.IP
.nf
\f[C]
* Red Hat Enterprise Linux

* Debian, Ubuntu

* Arch Linux
\f[R]
.fi
.RE
.TP
.B \f[B]--admin\f[R] \f[I]databases\f[R]
Through my work experiences I have become skilled in many database
languages including MySQL, PostgreSQL, SQLite, and SQL Server. These
experiences range from designing a full database schema, administrating
and managing an existing database, and writing queries to parse through
the data.
.TP
.B \f[B]--developer\f[R]
I have worked on several development projects in both work environments
and personally using a plethora of different programming languages and
paradigms
.TP
.B \f[B]--researcher\f[R]
While working at the Georgia Tech Research Institute, I have found that
I love being involved with research projects. I enjoy taking charge of
open ended questions and exploring new methods and ways of tackling
tough problems.
.SH PROJECTS
.PP
\f[B]SemanticModels.jl\f[R] -
<https://github.com/jpfairbanks/SemanticModels.jl>
.IP
.nf
\f[C]
* Researching and developing a novel methodology to programmatically
represent and manipulate scientific models at the semantic level

* Actively contribute and maintain this open source project coming out of
the Georgia Tech Research Institute sponsored by the Defense Advanced
Research Projects Agency (DARPA)
\f[R]
.fi
.PP
\f[B]Linux Configuration\f[R] -
<https://git.mehalter.com/mehalter/dotfiles>
.IP
.nf
\f[C]
* Configured and maintain a minimal Linux installation to meet my
development needs

* Developed many custom scripts to optimize my workflow
\f[R]
.fi
.SH NOTES
.PP
Outside of the field of computer science I have many hobbies and
passions including Ultimate Frisbee, coffee, and music.
.PP
At Georgia Tech and the greater Atlanta area, I am a very active member
of the Ultimate Frisbee community. This includes playing on multiple
competitive teams throughout the years and competing in tournaments
nationally and globally.
.PP
I have been an avid coffee enthusiast for several years, frequenting
many coffee shops, getting to know local coffee roasters and baristas,
and hand brewing my own craft coffee.
.PP
Growing up I was very involved with band and played many instruments
including piano and flute. Nowadays I don\[cq]t play very often, but
love to attend concerts and live music events.
.SH SEE ALSO
.PP
Phone: +1 704 490 9840
.PP
Email: <micah\[at]mehalter.com>
.PP
GPG: 532C 083C 2D6A 4752 46F1 8639 E10C 6AE7 BF5B 1D1F (https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xE10C6AE7BF5B1D1F)
.PP
Website: <https://mehalter.com>
.PP
Git: <https://git.mehalter.com/mehalter>
.SH AUTHORS
Micah Elliot Halter.
